### ISSUE TITLE
Uncaught exception for timeout

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/udi_python_interface#13]
```
2021-12-28 12:41:06,259 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2021-12-28 12:41:06,260 MainThread udi_interface      ERROR    udi_interface:write: File "./elk-poly.py", line 19, in <module>
2021-12-28 12:41:06,262 MainThread udi_interface      ERROR    udi_interface:write: control = Controller(polyglot, 'controller', 'controller', 'ELK Controller')
2021-12-28 12:41:06,262 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:21:b9:00:f8:c8_4/nodes/Controller.py", line 34, in __init__
2021-12-28 12:41:06,264 MainThread udi_interface      ERROR    udi_interface:write: self.poly.Notices.clear()
2021-12-28 12:41:06,264 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/custom.py", line 125, in clear
2021-12-28 12:41:06,266 MainThread udi_interface      ERROR    udi_interface:write: self._save()
2021-12-28 12:41:06,267 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/custom.py", line 36, in _save
2021-12-28 12:41:06,268 MainThread udi_interface      ERROR    udi_interface:write: self.poly.send(message, 'custom')
2021-12-28 12:41:06,269 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/interface.py", line 503, in send
2021-12-28 12:41:06,272 MainThread udi_interface      ERROR    udi_interface:write: LOGGER.error('MQTT Send timeout :: {}.'.format(messsage))
2021-12-28 12:41:06,272 MainThread udi_interface      ERROR    udi_interface:write: NameError
2021-12-28 12:41:06,273 MainThread udi_interface      ERROR    udi_interface:write: :
2021-12-28 12:41:06,274 MainThread udi_interface      ERROR    udi_interface:write: name 'messsage' is not defined
```

**Comment by bpaauwe** [comment]
Fixed typo.  will be included in version 3.0.30
